//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohwEmail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_UPLOADFILE_M
    {
        public string UPLOADFILE_SERIL_NO { get; set; }
        public string FORM_TYPE { get; set; }
        public string FORM_SERIL_NO { get; set; }
        public string ACT_TYPE { get; set; }
        public string ACT_PK1 { get; set; }
        public string ACT_PK2 { get; set; }
        public string ORIGINAL_FILENAME { get; set; }
        public string SAVE_FILEPATH { get; set; }
        public string SAVE_FILENAME { get; set; }
        public string FILE_DESC { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public System.DateTime CRE_DTE { get; set; }
        public string CRE_USR { get; set; }
        public Nullable<System.DateTime> MOD_DTE { get; set; }
        public string MOD_USR { get; set; }
        public string SUB_ANNEX_PK { get; set; }
    }
}
