//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohwEmail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPREL_GRP_GRPM
    {
        public string REL_DOMAIN_ID { get; set; }
        public string F_DOMAIN_ID { get; set; }
        public string F_COMP_ID { get; set; }
        public string F_GROUP_KIND { get; set; }
        public string F_GROUP_ID { get; set; }
        public string T_DOMAIN_ID { get; set; }
        public string T_COMP_ID { get; set; }
        public string T_GROUP_KIND { get; set; }
        public string T_GROUP_ID { get; set; }
        public string REL_KIND { get; set; }
        public string LINK_KIND { get; set; }
        public int LINK_DIST { get; set; }
        public string T_MBR_REL_DOMAIN_ID { get; set; }
        public string BOOLEAN_KIND { get; set; }
        public string IS_PUSH_UP { get; set; }
        public string IS_INC_FWD_MBR { get; set; }
        public string IS_INC_FWD_MGR { get; set; }
        public string IS_INC_ALL_MGR_REL { get; set; }
        public string IS_MANAGER { get; set; }
        public string SORT_ORDER { get; set; }
    }
}
