//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MohwEmail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWS_CLOSE_M
    {
        public string HANDLE_SERIL_NO { get; set; }
        public string SERVICE_SERIL_NO { get; set; }
        public string TEMP_SAVE_FLAG { get; set; }
        public string CLOSE_TYPE { get; set; }
        public Nullable<System.DateTime> CLOSE_DTE { get; set; }
        public string CLOSE_REMARK { get; set; }
        public string CLOSE_COMMENT { get; set; }
        public string CLOSE_SOURCE_CODE { get; set; }
        public string TRANSFERTO_FAQ_YN { get; set; }
        public string SATISFY_YN { get; set; }
        public System.DateTime CRE_DTE { get; set; }
        public string CRE_USR { get; set; }
        public System.DateTime MOD_DTE { get; set; }
        public string MOD_USR { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string FIELD_6 { get; set; }
        public string FIELD_7 { get; set; }
        public string FIELD_8 { get; set; }
        public string FIELD_9 { get; set; }
        public string FIELD_10 { get; set; }
    }
}
